// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('titleText', { text: 'Upcoming Recordings' });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateScrollArea('scrollArea', { spacing: 4, hasVerticalScrollbar: true });
    CreateText('backendString', { text: 'backendIP' });
    CreateText('portString', { text: 'port' });
    CreateText('statusText', {  });
    CreateText('versionString', { text: 'VERSION' });
    CreateText('copyrightString', { text: 'COPYRIGHT' });
    CreateText('urlString', { text: 'http://www.c99.org/' });
    CreateShape('topRectangleShape7', { rightImageWidth: 10, leftImageWidth: 10 });
}
window.addEventListener('load', setupParts, false);
